### ISSUE TITLE
Crash when entering Character-Sheet on installation with limited Scopes

### ISSUE THREAD

**Issue by bkrauss** [eveseat/seat#400]
**Problem**: _EVE-SeAT crashes, when entering Character-Sheet on Installation with limited Scopes_
**Expected**: _The sheet to appear with the data (using the scopes configured)._
**Logs / Screenshots / Proof**: 
Basics:
We've setup a SeAT-Installation for the review of people who want to join our corp. For privacy reasons we don't want to make them naked, so we decided to limit the scopes of our API-Access to the absolute neccesary Informations. The Installation runs as set of docker containers (composition file is attached) with the official images provided. The scopes has been configured in the EVE AppManagement as well as in the SeAT Application itself.

Proof:
![eve_app_config](https://user-images.githubusercontent.com/41026106/42478870-9a129f7e-83d6-11e8-8c8e-79c639c32716.jpg)

![seat_scopes](https://user-images.githubusercontent.com/41026106/42478471-20879624-83d5-11e8-825f-0d6f3bba71c6.jpg)

List of configured scopes:

> esi-mail.read_mail.v1
> esi-skills.read_skills.v1
> esi-skills.read_skillqueue.v1
> esi-wallet.read_character_wallet.v1
> esi-clones.read_clones.v1
> esi-characters.read_contacts.v1
> esi-killmails.read_killmails.v1
> esi-characters.read_standings.v1
> esi-characters.read_corporation_roles.v1
> esi-contracts.read_character_contracts.v1
> esi-characters.read_fatigue.v1
> esi-characterstats.read.v1

Steps to reproduce:
![stepstoreproduce](https://user-images.githubusercontent.com/41026106/42477864-0cbedfc8-83d3-11e8-9c28-c13ded71cc29.jpg)

Full Message in Debugmode:
![Message](https://user-images.githubusercontent.com/41026106/42476932-c953c3a0-83cf-11e8-9b86-2c0c67acad43.jpg)

Compose file for Docker setup:
```
version: "2"

services:

  mariadb:
    image: mariadb:10.3
    container_name: seat-mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - "mariadb-data:/var/lib/mysql"
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  redis:
    image: redis:3
    container_name: seat-redis
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - "redis-data:/data"
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  nginx:
    image: eveseat/eveseat-nginx:latest
    depends_on:
      - seat-app
    container_name: seat-nginx
    restart: always
    environment:
      - NGINX_HOST=${NGINX_HOST}
    volumes:
      - "seat-code:/var/www/seat"
      # Remove the comment below to enable nginx logs to disk.
      #- ./logs/nginx/:/var/log/nginx/
    command: /bin/sh -c "envsubst '${NGINX_HOST}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    labels:
        - "traefik.frontend.rule=Host:review.some-eve-corp.de"
        - "traefik.docker.network=Traefik"
        - "traefik.port=80"
        - "traefik.enable=true"
        - "traefik.frontend.headers.SSLRedirect=true"
    networks:
      - seat-network
      - Traefik
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  seat-app:
    image: eveseat/eveseat-app:latest
    container_name: seat-app
    restart: always
    environment:
      DB_HOST: mariadb
      REDIS_HOST: redis
    env_file:
      - ./.env
    volumes:
      - "seat-code:/var/www/seat"
      # Remove the comment below to enable SeAT logs to disk.
      #- ./logs:/var/www/seat/storage/logs
    depends_on:
      - mariadb
      - redis
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  seat-worker:
    image: eveseat/eveseat-worker:latest
    container_name: seat-worker
    restart: always
    environment:
      DB_HOST: mariadb
      REDIS_HOST: redis
    env_file:
      - ./.env
    volumes:
      - "seat-code:/var/www/seat"
    depends_on:
      - seat-app # for the seat-code volume
      - mariadb
      - redis
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  seat-cron:
    image: eveseat/eveseat-cron:latest
    container_name: seat-cron
    restart: always
    environment:
      DB_HOST: mariadb
      REDIS_HOST: redis
    env_file:
      - ./.env
    volumes:
      - "seat-code:/var/www/seat"
    depends_on:
      - seat-app # for the seat-code volume
      - mariadb
      - redis
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

volumes:
    seat-code:
    redis-data:
    mariadb-data:

networks:
    seat-network:
    Traefik:
      external: true
```

**Version Info**: _Current Docker Image / Web Version 3.0.3 / SDE Version sde-20180529-TRANQUILITY_

It would be nice, if someone could help me to get the installation with the limited scopes to work.
